version: "3.8"
services: 
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: thiagodb
    volumes: 
      - ./db/data:/var/lib/mysql
    restart: always
  api:
    build: "./api"
    container_name: nodejs-container
    ports: 
      - "8080:8080"
    depends_on: 
      - db
    restart: always

